version: '3.9'

services:
  db:
    image: postgres:15
    container_name: salary-db
    restart: always
    env_file:
      - .env
    environment:
      # Переменные для инициализации БД
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: salary-web
    restart: on-failure
    depends_on:
      - db
    env_file:
      - .env
    environment:
      # Переопределяем хост БД на имя контейнера
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
    ports:
      - "8000:8000"
    command: >
      /bin/sh -c "
        # дождаться поднятия Postgres (простая задержка):
        sleep 5 &&
        # применить миграции
        alembic -c /app/alembic.ini upgrade head &&
        # запустить приложение
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

volumes:
  db_data:
