"""update next_raise_date

Revision ID: 8d66a3833d69
Revises: 92103a121987
Create Date: 2025-06-22 20:24:28.865326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d66a3833d69'
down_revision: Union[str, Sequence[str], None] = '92103a121987'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'next_raise_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'next_raise_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
