"""add CASCADE

Revision ID: a947e9daab88
Revises: 5ccdea9d79cf
Create Date: 2025-06-24 12:16:27.153962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a947e9daab88'
down_revision: Union[str, Sequence[str], None] = '5ccdea9d79cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salary', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'salary', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salary', type_='foreignkey')
    op.drop_column('salary', 'user_id')
    # ### end Alembic commands ###
